import type { Metadata } from "next";

export const keywords = [
  "Tycoonz Solutions, Tycoonz, Tycoon, Tycoonz Solutions",
  "Tycoonz Solutions",
  "Software development company in Lahore",
  "Blockchain solutions provider",
  "Web3.0 integration services",
  "Mobile app development",
  "Custom software solutions",
  "Digital transformation agency",
  "Blockchain development",
  "Decentralized applications (DApps)",
  "Smart contract development",
  "NFT integration services",
  "Crypto payment solutions",
  "Distributed ledger technology (DLT)",
  "Decentralized systems",
  "Healthcare technology solutions",
  "AI-powered software development",
  "Enterprise application development",
  "Cloud-based solutions for businesses",
  "Global tech solutions provider",
  "Tailored digital solutions for businesses",
  "Client retention in software development",
  "Innovative technology for business growth",
  "System audits and strategic planning",
  "Blockchain security audits",
  "Training and support services",
  "Navigating the future with blockchain technology",
  "Cutting-edge tech solutions for businesses",
  "Transforming ideas into reality through innovation",
  "Cross-platform app development",
  "Blockchain consulting services",
  "Web3.0 strategy and implementation",
  "Decentralized finance (DeFi) solutions",
  "Non-fungible token (NFT) marketplace development",
  "Cryptocurrency integration services",
  "Blockchain-based supply chain management",
  "AI-driven healthcare solutions",
  "Cloud migration and management",
  "Enterprise software development",
  "Custom mobile app design",
  "Blockchain security and auditing",
  "Web3.0 decentralized applications",
  "Digital asset management",
  "Blockchain for IoT",
  "Artificial intelligence in healthcare",
  "Machine learning solutions",
  "Blockchain-based identity verification",
  "Decentralized data storage solutions",
  "Web3.0 community building",
  "Blockchain for social impact",
  "Custom blockchain networks",
  "Blockchain interoperability solutions",
  "Web3.0 gaming development",
  "NFT art marketplace development",
  "Blockchain-based cybersecurity solutions",
  "Blockchain development company",
  "Web3.0 software development services",
  "Smart contract development company",
  "AI-powered business automation",
  "Custom enterprise software development",
  "Decentralized application (DApp) development",
  "Secure mobile app development solutions",
  "Blockchain-based payment solutions",
  "Crypto token development & consulting",
  "NFT marketplace development company",
  "Best blockchain development company for startups",
  "Web3.0 gaming development services",
  "Enterprise AI & blockchain solutions",
  "Healthcare software development company",
  "Cloud-based application development",
  "Machine learning & AI software services",
  "Decentralized finance (DeFi) development",
  "Cross-platform mobile app development",
  "Blockchain security & smart contract auditing",
  "Blockchain-based identity verification solutions",
  "Software development company in Lahore",
  "Blockchain technology experts in Pakistan",
  "AI & Web3 software development in UAE",
  "Enterprise IT solutions provider in Pakistan",
  "Decentralized finance (DeFi) experts in the Middle East",
  "Blockchain development company in Europe",
  "Top Web3 & AI software development in North America",
  "Custom software development company in the USA & Canada",
  "Fintech blockchain solutions provider in the UK",
  "Best AI-driven enterprise solutions in Germany & Europe",
  "Blockchain development company",
  "Web3.0 software development services",
  "Smart contract development company",
  "AI-powered business automation",
  "Custom enterprise software development",
  "Decentralized application (DApp) development",
  "Secure mobile app development solutions",
  "Blockchain-based payment solutions",
  "Crypto token development & consulting",
  "NFT marketplace development company",
  "Blockchain consulting services",
  "Web3.0 strategy and implementation",
  "Decentralized finance (DeFi) solutions",
  "Non-fungible token (NFT) marketplace development",
  "Cryptocurrency integration services",
  "Blockchain-based supply chain management",
  "AI-driven healthcare solutions",
  "Cloud migration and management",
  "Enterprise software development",
  "Custom mobile app design",
  "Blockchain security and auditing",
  "Web3.0 decentralized applications",
  "Digital asset management",
  "Blockchain for IoT",
  "Artificial intelligence in healthcare",
  "Machine learning solutions",
  "Blockchain-based identity verification",
  "Decentralized data storage solutions",
  "Web3.0 community building",
  "Blockchain for social impact",
  "Custom blockchain networks",
  "Blockchain interoperability solutions",
  "Web3.0 gaming development",
  "NFT art marketplace development",
  "Blockchain-based cybersecurity solutions",
  "Best blockchain development company for startups",
  "Web3.0 gaming development services",
  "Enterprise AI & blockchain solutions",
  "Healthcare software development company",
  "Cloud-based application development",
  "Machine learning & AI software services",
  "Decentralized finance (DeFi) development",
  "Cross-platform mobile app development",
  "Blockchain security & smart contract auditing",
  "Blockchain-based identity verification solutions",
  "AI-powered fintech solutions",
  "Blockchain for real estate",
  "Web3.0 social media platform development",
  "Decentralized data analytics",
  "Blockchain-based cybersecurity consulting",
  "AI-driven customer service solutions",
  "Web3.0 e-commerce platform development",
  "Blockchain for supply chain management",
  "AI-powered predictive maintenance",
  "Blockchain-based digital identity solutions",
  "Software development company in Lahore",
  "Blockchain technology experts in Pakistan",
  "AI & Web3 software development in UAE",
  "Enterprise IT solutions provider in Pakistan",
  "Decentralized finance (DeFi) experts in the Middle East",
  "Blockchain development company in Europe",
  "Top Web3 & AI software development in North America",
  "Custom software development company in the USA & Canada",
  "Fintech blockchain solutions provider in the UK",
  "Best AI-driven enterprise solutions in Germany & Europe",
  "Blockchain consulting services in Australia",
  "Web3.0 development company in Asia",
  "AI-powered software solutions in Africa",
  "Blockchain-based payment solutions in Latin America",
  "Custom blockchain development in India",
  "Best AI-powered blockchain solutions for fintech companies",
  "Custom decentralized finance (DeFi) app developers",
  "Blockchain-based cybersecurity solutions for enterprises",
  "Web3.0 gaming development services for startups",
  "AI-driven healthcare software development company",
  "Cloud-based blockchain solutions for supply chain management",
  "Machine learning & AI software services for predictive maintenance",
  "Decentralized data storage solutions for IoT devices",
  "Blockchain-based identity verification for social media platforms",
  "Custom blockchain networks for enterprise use cases",
  "Blockchain interoperability solutions for cross-chain transactions",
  "Web3.0 community building for social impact projects",
  "Blockchain for social impact in developing countries",
];

export const metadataObj: Metadata = {
  title: "Tycoonz Solutions",
  description: "Tycoonz Solutions - Navigating the Future.",
  keywords,
  robots: "follow, index",
  category:
    "Technology, Developer, Blockchain, Web3, AI, Crypto, Fintech, NFT, DeFi, Enterprise",
  openGraph: {
    title: "Tycoonz Solutions",
    description: "Tycoonz Solutions - Navigating the Future.",
    phoneNumbers: "+923174144853",
    emails: "info@tycoonzsolutions.com",
    countryName: "Pakistan",
    images: [],
    type: "website",
    locale: "en_US",
    siteName: "Tycoonz Solutions",
    url: "https://tycoonzsolutions.com",
    alternateLocale: "en_US",
    determiner: "the",
  },
  facebook: {
    appId: "9372125112870007",
  },
  manifest: new URL("https://tycoonzsolutions.com"),
};
